<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace SmartEditorPo\DataSource\Language;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class LanguageTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'language';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'id',
            'language',
            'lang_code',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'id' => (object) [
                'name' => 'id',
                'type' => 'bigint',
                'size' => 20,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'language' => (object) [
                'name' => 'language',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'lang_code' => (object) [
                'name' => 'lang_code',
                'type' => 'varchar',
                'size' => 20,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'id' => null,
            'language' => null,
            'lang_code' => null,
        ];
    }
}
