###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: pomanager-node-redis

    node:
      build: node
      container_name: pomanager-node-node
      stdin_open: true
      tty: true
      ports:
       - "1070:9080"
       - "5858:5858"
       - "8082:80"
       - "3001:3001"
       - "3002:3002"       
      volumes:
       - ./srcjs/:/usr/src/app/
      environment:
       - NODE_ENV=dev

     
    mongo:
      image: mongo:3.4.10-jessie  
      container_name: pomanager-node-mongo    
      ports:
        - "27017:27017"
      
    mongoclient:
      image: mongo-express:latest
      container_name: pomanager-node-mongo-client
      depends_on:
        - mongo
      environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=root
       - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      ports:
        - "8081:8081"

    webserver:
      image: nginx:latest
      container_name: pomanager-node-webserver
      working_dir: /application
      volumes:
          - ./srcjs/php:/application
          - ./phpdocker/nginx/:/etc/nginx/conf.d/
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: pomanager-node-php-fpm
      working_dir: /application
      volumes:
        - ./srcjs/php:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini        
  
