###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: pomanager-node-redis

    webserver:
      image: nginx:latest
      container_name: pomanager-node-webserver
      working_dir: /application
      volumes:
          - ./sourcecode:/application
          - ./phpdocker/nginx/:/etc/nginx/conf.d/
      ports:
       - "80:80"
    mysql:
      image: mysql:8.0
      container_name: pomanager-node-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=r083rt0
        - MYSQL_DATABASE=indici
        - MYSQL_USER=indici
        - MYSQL_PASSWORD=indici
      ports:
        - "3306:3306"
    php-fpm:
      build: phpdocker/php-fpm
      container_name: pomanager-node-php-fpm
      working_dir: /application
      volumes:
        - ./sourcecode:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini   
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pomanager-node-phpmyadmin
      restart: always
      environment:
       - PMA_HOSTS=mysql,127.0.0.1
      ports:
       - "8081:80"
  
